---
- name: Create Pi-hole configuration directories
  file:
    path: '{{ dir_loc }}/{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items:
    - /etc/pihole
    - /etc/dnsmasq.d
  become: true
